/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SmartMatchingRouteImport } from './routes/smart-matching'
import { Route as FindHospitalsRouteImport } from './routes/find-hospitals'
import { Route as FindDoctorsRouteImport } from './routes/find-doctors'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as AiAssistantRouteImport } from './routes/ai-assistant'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'
import { Route as AuthenticatedDashboardPatientRouteImport } from './routes/_authenticated/dashboard.patient'
import { Route as AuthenticatedDashboardHospitalRouteImport } from './routes/_authenticated/dashboard.hospital'
import { Route as AuthenticatedDashboardDonorRouteImport } from './routes/_authenticated/dashboard.donor'
import { Route as AuthenticatedDashboardAdminRouteImport } from './routes/_authenticated/dashboard.admin'

const SmartMatchingRoute = SmartMatchingRouteImport.update({
  id: '/smart-matching',
  path: '/smart-matching',
  getParentRoute: () => rootRouteImport,
} as any)
const FindHospitalsRoute = FindHospitalsRouteImport.update({
  id: '/find-hospitals',
  path: '/find-hospitals',
  getParentRoute: () => rootRouteImport,
} as any)
const FindDoctorsRoute = FindDoctorsRouteImport.update({
  id: '/find-doctors',
  path: '/find-doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArticlesRoute,
} as any)
const AuthenticatedDashboardPatientRoute =
  AuthenticatedDashboardPatientRouteImport.update({
    id: '/dashboard/patient',
    path: '/dashboard/patient',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardHospitalRoute =
  AuthenticatedDashboardHospitalRouteImport.update({
    id: '/dashboard/hospital',
    path: '/dashboard/hospital',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardDonorRoute =
  AuthenticatedDashboardDonorRouteImport.update({
    id: '/dashboard/donor',
    path: '/dashboard/donor',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardAdminRoute =
  AuthenticatedDashboardAdminRouteImport.update({
    id: '/dashboard/admin',
    path: '/dashboard/admin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/find-doctors': typeof FindDoctorsRoute
  '/find-hospitals': typeof FindHospitalsRoute
  '/smart-matching': typeof SmartMatchingRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/dashboard/donor': typeof AuthenticatedDashboardDonorRoute
  '/dashboard/hospital': typeof AuthenticatedDashboardHospitalRoute
  '/dashboard/patient': typeof AuthenticatedDashboardPatientRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/find-doctors': typeof FindDoctorsRoute
  '/find-hospitals': typeof FindHospitalsRoute
  '/smart-matching': typeof SmartMatchingRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/dashboard/donor': typeof AuthenticatedDashboardDonorRoute
  '/dashboard/hospital': typeof AuthenticatedDashboardHospitalRoute
  '/dashboard/patient': typeof AuthenticatedDashboardPatientRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/ai-assistant': typeof AiAssistantRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/find-doctors': typeof FindDoctorsRoute
  '/find-hospitals': typeof FindHospitalsRoute
  '/smart-matching': typeof SmartMatchingRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/_authenticated/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/_authenticated/dashboard/donor': typeof AuthenticatedDashboardDonorRoute
  '/_authenticated/dashboard/hospital': typeof AuthenticatedDashboardHospitalRoute
  '/_authenticated/dashboard/patient': typeof AuthenticatedDashboardPatientRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-assistant'
    | '/articles'
    | '/auth'
    | '/contact'
    | '/find-doctors'
    | '/find-hospitals'
    | '/smart-matching'
    | '/articles/$slug'
    | '/dashboard/admin'
    | '/dashboard/donor'
    | '/dashboard/hospital'
    | '/dashboard/patient'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-assistant'
    | '/articles'
    | '/auth'
    | '/contact'
    | '/find-doctors'
    | '/find-hospitals'
    | '/smart-matching'
    | '/articles/$slug'
    | '/dashboard/admin'
    | '/dashboard/donor'
    | '/dashboard/hospital'
    | '/dashboard/patient'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/ai-assistant'
    | '/articles'
    | '/auth'
    | '/contact'
    | '/find-doctors'
    | '/find-hospitals'
    | '/smart-matching'
    | '/articles/$slug'
    | '/_authenticated/dashboard/admin'
    | '/_authenticated/dashboard/donor'
    | '/_authenticated/dashboard/hospital'
    | '/_authenticated/dashboard/patient'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AiAssistantRoute: typeof AiAssistantRoute
  ArticlesRoute: typeof ArticlesRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  FindDoctorsRoute: typeof FindDoctorsRoute
  FindHospitalsRoute: typeof FindHospitalsRoute
  SmartMatchingRoute: typeof SmartMatchingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/smart-matching': {
      id: '/smart-matching'
      path: '/smart-matching'
      fullPath: '/smart-matching'
      preLoaderRoute: typeof SmartMatchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-hospitals': {
      id: '/find-hospitals'
      path: '/find-hospitals'
      fullPath: '/find-hospitals'
      preLoaderRoute: typeof FindHospitalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-doctors': {
      id: '/find-doctors'
      path: '/find-doctors'
      fullPath: '/find-doctors'
      preLoaderRoute: typeof FindDoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-assistant': {
      id: '/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/_authenticated/dashboard/patient': {
      id: '/_authenticated/dashboard/patient'
      path: '/dashboard/patient'
      fullPath: '/dashboard/patient'
      preLoaderRoute: typeof AuthenticatedDashboardPatientRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/hospital': {
      id: '/_authenticated/dashboard/hospital'
      path: '/dashboard/hospital'
      fullPath: '/dashboard/hospital'
      preLoaderRoute: typeof AuthenticatedDashboardHospitalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/donor': {
      id: '/_authenticated/dashboard/donor'
      path: '/dashboard/donor'
      fullPath: '/dashboard/donor'
      preLoaderRoute: typeof AuthenticatedDashboardDonorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/admin': {
      id: '/_authenticated/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof AuthenticatedDashboardAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardAdminRoute: typeof AuthenticatedDashboardAdminRoute
  AuthenticatedDashboardDonorRoute: typeof AuthenticatedDashboardDonorRoute
  AuthenticatedDashboardHospitalRoute: typeof AuthenticatedDashboardHospitalRoute
  AuthenticatedDashboardPatientRoute: typeof AuthenticatedDashboardPatientRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardAdminRoute: AuthenticatedDashboardAdminRoute,
  AuthenticatedDashboardDonorRoute: AuthenticatedDashboardDonorRoute,
  AuthenticatedDashboardHospitalRoute: AuthenticatedDashboardHospitalRoute,
  AuthenticatedDashboardPatientRoute: AuthenticatedDashboardPatientRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ArticlesRouteChildren {
  ArticlesSlugRoute: typeof ArticlesSlugRoute
}

const ArticlesRouteChildren: ArticlesRouteChildren = {
  ArticlesSlugRoute: ArticlesSlugRoute,
}

const ArticlesRouteWithChildren = ArticlesRoute._addFileChildren(
  ArticlesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AiAssistantRoute: AiAssistantRoute,
  ArticlesRoute: ArticlesRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  FindDoctorsRoute: FindDoctorsRoute,
  FindHospitalsRoute: FindHospitalsRoute,
  SmartMatchingRoute: SmartMatchingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
